### ISSUE TITLE
SMFC hardware compatibility

### ISSUE THREAD

**Issue by petersulyok** [petersulyok/smfc#19]
This thread is a collection of the compatibility feedbacks.
Please leave a comment here with the name of your Super Micro motherboard if you:

1. successfully executed SMFC

or 

2. you tried and failed because of a compatibility issue

Thanks for your feedback.

**Comment by petersulyok** [comment]
Super Micro X11SCH-F motherboard is OK.

**Comment by petersulyok** [comment]
@thiete reported Super Micro X11SPI-TF motherboard.

**Comment by secabeen** [comment]
Works great on my X11SAE-F-O

**Comment by alexhelms** [comment]
I have a 6028U-TR4T+ server with the X10DRU-i+ motherboard and SMFC partially works. There are 9 fan headers but 4 populated fans in the chassis. Fans 1 and 2 are for CPU1 and fans 7 and 8 are for CPU2 (according to ipmitool). The other fan headers are unpopulated. I believe there are two CPU zones and no HD zones. I tried with with `swapped_zones=0` and it only controlled fans 1 and 2. I changed to `swapped_zones=1` and now fans 7 and 8 were controlled.

Is there a way to configure two cpu zones?

**Comment by petersulyok** [comment]
Hi @alexhelms! Please continue the discussion about your  X10DRU-i+ motherboard in issue #20

**Comment by staaled** [comment]
**Supermicro H13SSL-NT**

With an AMD EPYC Genoa CPU seems to work just fine (a little guesswork with temperature sensors/paths though).

I have my chassis fans on connectors FAN[1-4], and CPU on FANA, with `swapped_zones=1`

(sidenote: setting custom thresholds for fans warn/crit levels etc didn't work out of the box but haven't had time to investigate, the defaults work)

**Comment by Rhyolite1** [comment]
Supermicro X11SCH-LN4, I'm having the same issue as https://github.com/petersulyok/smfc/issues/21 I will await your update to fix the issue as noted in the thread. Thank you for making this! I've spent a month trying to solve my fan rpm oscillation issue.

**Comment by petersulyok** [comment]
> Supermicro X11SCH-LN4, I'm having the same issue as #21 I will await your update to fix the issue as noted in the thread. Thank you for making this! I've spent a month trying to solve my fan rpm oscillation issue.

The update is available on the main branch, you may test to see if it works with your config (SCSI/SAS drives it require `hddtemp`).

**Comment by Rhyolite1** [comment]
> > Supermicro X11SCH-LN4, I'm having the same issue as #21 I will await your update to fix the issue as noted in the thread. Thank you for making this! I've spent a month trying to solve my fan rpm oscillation issue.
> 
> The update is available on the main branch, you may test it to check if it works with your config (SCSI/SAS drives require `hddtemp`).

**Comment by petersulyok** [comment]
> Supermicro X11SCH-LN4, I'm having the same issue as #21 I will await your update to fix the issue as noted in the thread. Thank you for making this! I've spent a month trying to solve my fan rpm oscillation issue.

Please continue the discussion in issue #21.

**Comment by petersulyok** [comment]
X11SCH-LN4 is working fine for @Rhyolite1.

**Comment by veita** [comment]
Seems to work on SuperServer E300-9A with A2SDi-TP8F single processor motherboard.

**Comment by u-w-e-h** [comment]
Works perfect @ A2SDi-H-TPTF motherboard.

**Comment by hcgonzalezpr** [comment]
Board: **X13SAE-F** 

Board Fan Names:  `CPU_FAN1  |  CPU_FAN2  |  SYS_FAN1  |  SYS_FAN2  |  SYS_FAN3`
 
| Script Name | Status | Notes |
| -------- | ------- | ------- |
| set_ipmi_fan_level.sh | Works | The zones are still the same and the script works as intended |
| fan_measurement.sh | Works [Mod] | Needs to have FAN names updated, sleep set to 10sec to give enough time to slow down and sometimes set speed will error with `Get Device ID command failed: 0xff Unspecified error` `Received a response with unexpected ID 0 vs. 1` |
| set_ipmi_threshold.sh | Errors | Even with the FANs named properly anything beside `Lower Critical Error` throws the following error  `Command illegal for specified sensor or record type` and fails to apply the failed values. |
| set_ipmi_fan_mode.sh | Works | No changes needed |
| ipmi_bmc_reset.sh | Works | No changes needed. Reports: `Length of the BMC cold reset cycle was 74 seconds.`|

@petersulyok I only tested the ipmi scripts, I have not run the full solution, let me know if you want me to test something else.

**Comment by petersulyok** [comment]
> Board: **X13SAE-F**

Please follow the discussion here, at #33.

**Comment by hcgonzalezpr** [comment]
Here the output from `ipmitool sensor | grep FAN`,  the `Lower Critical Error` goes to the closest available value set.

Output :
`CPU_FAN1         | 980.000    | RPM        | ok    | na        | 140.000   | na        | na        | na        | na
CPU_FAN2         | 980.000    | RPM        | ok    | na        | 140.000   | na        | na        | na        | na
SYS_FAN1         | 840.000    | RPM        | ok    | na        | 140.000   | na        | na        | na        | na
SYS_FAN2         | 840.000    | RPM        | ok    | na        | 140.000   | na        | na        | na        | na
SYS_FAN3         | 840.000    | RPM        | ok    | na        | 140.000   | na        | na        | na        | na`

**Comment by petersulyok** [comment]
As it was reported above, `smfc` is running on Super Micro X13SAE-F. AST2600 has only one fan threshold sensor - Upper Critical, other thresholds are not implemented.

**Comment by hcgonzalezpr** [comment]
> As it was reported above by @hcgonzalezpr, `smfc` is running on Super Micro X13SAE-F. AST2600 has only one fan threshold sensor (Upper Critical), other thresholds are not implemented.

I think you got a typo, only Lower Critical is able to be set.

**Comment by petersulyok** [comment]
> I think you got a typo, only Lower Critical is able to be set.

Thanks indeed [my comment](https://github.com/petersulyok/smfc/issues/19#issuecomment-1960512967) has been edited/corrected.

**Comment by thisisnotmyrealname** [comment]
H11SSL-NC used in a SC846/847 chassis and with an external 44 bay supermicro jbod.

Was failing to start

Maybe a sanity check for people who can't read and are just using the ./smfc.py script to ensure the drivetemp module is loaded?

**Comment by petersulyok** [comment]
> Maybe a sanity check for people who can't read and are just using the ./smfc.py script to ensure the drivetemp module is loaded?

Good idea, now v3.5.0 does this.

**Comment by taoning** [comment]
H13SRA-TF not responding to change in fan speed. smfc.serivce is running without error. All fans stayed at 100%

**Comment by emansom** [comment]
> H13SRA-TF not responding to change in fan speed. smfc.serivce is running without error. All fans stayed at 100%

Try a full power off and on cycle after changing the fan mode and fan min & max PWM values, this worked for me.

**Comment by taoning** [comment]
> Try a full power off and on cycle after changing the fan mode and fan min & max PWM values, this worked for me.
Tried full power off and on, fan ramped to 100% within a few seconds after booting into OS.  I can only set lower critical RPM through IPMI.  Not sure how to set PWM values?

**Comment by emansom** [comment]
> nvm, it works now, thanks for the tip.

@taoning

Make sure lower critical RPM is at least 10% lower than the lowest RPM defined on the fan spec sheet, accounting for manufacturing tolerances and rounded to closest hundred.

So if lowest RPM on spec sheet of the fan is 450 RPM, and the manufacturer tolerances are 25%, then the lower critical RPM should be set to: (450/100) * (100-(25+10)) = 292.5, rounded to a hundred is 300.

**Comment by vecinohk** [comment]
**A2SDi-4C-HLN4F** + Noctua NF-P12 redux-1700 PWM

It works perfectly - I am very satisfied. **Thanks to all of you who contributed to the development of this great helper**.

**Comment by Xyz00777** [comment]
trying to get it working for my `H11SSL-i` with ASPEED AST2500.
because im not sure with fans are connected on what pwm i tried to set lower to 500 for every fan and 2000 as upper limit for every fan in the config
```
# This script must be executed by root.
if [ "$EUID" -ne 0 ]
then
    echo "ERROR: Please run as root"
    exit -1
fi

# Setup of the lower threshold limits of the fans (Noctua NF-F12 PWM rotation speed 300-1500 rpm).
# Edit the list of fans here (FAN1, FAN2, FAN4, FANA, FANB)!
for i in 1 2 3 5 A B;
do
    # Edit the lower threshold values here (0, 100, 200)!
    ipmitool sensor thresh FAN${i} lower 500 500 500 500 500 500
done

# Setup of the upper threshold limits of the fans (Noctua NF-F12 PWM rotation speed 300-1500 rpm).
# Edit the list of fans here (FAN1, FAN2, FAN4, FANA, FANB)!
for i in 1 2 3 5 A B;
do
    # Edit the upper threshold values here (1600, 1700, 1800)!
    ipmitool sensor thresh FAN${i} upper 2000 2000 2000 2000 2000 2000
done
```
i have Iceberg Thermal IceGALE Xtra with 500-2500 rpm and Noctua NH-U9 TR4-SP3 with 400-2000 rpm


after i loaded the modules and executed the install.sh file i have startet the service and got these journalctl log and the service crashed with 100% fan speed

```
May 31 03:07:18 ds9 systemd[1]: Started smfc.service - Super Micro Fan Control.
May 31 03:07:18 ds9 smfc.service[11931]: Logging module was initialized with:
May 31 03:07:18 ds9 smfc.service[11931]:    log_level = 3
May 31 03:07:18 ds9 smfc.service[11931]:    log_output = 2
May 31 03:07:18 ds9 smfc.service[11931]: Command line arguments:
May 31 03:07:18 ds9 smfc.service[11931]:    original arguments: /opt/smfc/smfc.py -c /opt/smfc/smfc.conf -l 3
May 31 03:07:18 ds9 smfc.service[11931]:    parsed config file = /opt/smfc/smfc.conf
May 31 03:07:18 ds9 smfc.service[11931]:    parsed log level = 3
May 31 03:07:18 ds9 smfc.service[11931]:    parsed log output = 2
May 31 03:07:19 ds9 smfc.service[11931]: Ipmi module was initialized with:
May 31 03:07:19 ds9 smfc.service[11931]:    command = /usr/bin/ipmitool
May 31 03:07:19 ds9 smfc.service[11931]:    fan_mode_delay = 10
May 31 03:07:19 ds9 smfc.service[11931]:    fan_level_delay = 2
May 31 03:07:19 ds9 smfc.service[11931]:    swapped_zones = False
May 31 03:07:29 ds9 smfc.py[11931]: Traceback (most recent call last):
May 31 03:07:29 ds9 smfc.py[11931]:   File "/opt/smfc/smfc.py", line 1150, in <module>
May 31 03:07:29 ds9 smfc.py[11931]:     service.run()
May 31 03:07:29 ds9 smfc.py[11931]:   File "/opt/smfc/smfc.py", line 1119, in run
May 31 03:07:29 ds9 smfc.py[11931]:     self.cpu_zone = CpuZone(self.log, self.ipmi, self.config)
May 31 03:07:29 ds9 smfc.py[11931]:                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
May 31 03:07:29 ds9 smfc.py[11931]:   File "/opt/smfc/smfc.py", line 600, in __init__
May 31 03:07:29 ds9 smfc.py[11931]:     super().__init__(
May 31 03:07:29 ds9 smfc.py[11931]:   File "/opt/smfc/smfc.py", line 395, in __init__
May 31 03:07:29 ds9 smfc.py[11931]:     self.build_hwmon_path(hwmon_path)
May 31 03:07:29 ds9 smfc.py[11931]:   File "/opt/smfc/smfc.py", line 632, in build_hwmon_path
May 31 03:07:29 ds9 smfc.py[11931]:     raise ValueError(self.ERROR_MSG_FILE_IO.format(path))
May 31 03:07:29 ds9 smfc.py[11931]: ValueError: Cannot read file (/sys/devices/platform/coretemp.0/hwmon/hwmon*/temp1_input).
May 31 03:07:33 ds9 smfc.service[11931]: smfc terminated: all fans are switched back to the 100% speed.
May 31 03:07:33 ds9 systemd[1]: smfc.service: Main process exited, code=exited, status=1/FAILURE
May 31 03:07:33 ds9 systemd[1]: smfc.service: Failed with result 'exit-code'.
```

Please help i dont want my fans to spin up every ~10 sec for 5 sec :(

**Comment by petersulyok** [comment]
Hi @Xyz00777, please continue the dicussion in #37.

**Comment by kevinfason** [comment]
836 with X10SRi-F - working but need to do some adjusting. Its bouncing between 25% and 40% for a 3 degree change.

This mainboard has 6 fan headers. FAN1-5,A. Per SM docs FAN1 is CPU which is Dynatron R27. 2-4 are FAN-0126L4 and 5-A are FAN-0125L4. I adjusted the conf and set_ipmi_threshold.sh for this. 

`FAN1             | 1700.000   | RPM        | ok    | 200.000   | 300.000   | 500.000   | 25300.000 | 25400.000 | 25500.000
FAN2             | 4100.000   | RPM        | ok    | 200.000   | 300.000   | 500.000   | 25300.000 | 25400.000 | 25500.000
FAN3             | 3800.000   | RPM        | ok    | 200.000   | 300.000   | 500.000   | 25300.000 | 25400.000 | 25500.000
FAN4             | 3800.000   | RPM        | ok    | 200.000   | 300.000   | 500.000   | 25300.000 | 25400.000 | 25500.000
FAN5             | 4100.000   | RPM        | ok    | 200.000   | 300.000   | 500.000   | 25300.000 | 25400.000 | 25500.000
FANA             | 2300.000   | RPM        | ok    | 200.000   | 300.000   | 500.000   | 25300.000 | 25400.000 | 25500.000
`

Next time I power it down I'll get the actual fan manufacturer to look at their spec sheets. This is a ProxMox with the controller passed to a TrueNAS CORE VM. Has 2 NVMe m.2. To get FANA going I put in a SATA SSD and declared it in the conf even though it stated ATA would be auto. I'm moving away from the NVMe to SATA so this will help that zone. Also thought of going back to passive CPU to keep on CPU zone.

Min is set to 10% but I did a capture down to 5.
`Level,FAN1,FAN2,FAN3,FAN4,FAN5,FANA
100,4200,6800,7000,7000,7100,
95,4200,6800,6900,6900,7000,
90,4100,6500,6300,6500,6800,
85,3800,6300,6100,6200,6400,
80,3500,6100,5900,6000,6100,
75,3300,5900,5600,5600,5900,
70,3100,5600,5400,5400,5500,
65,2800,5400,5100,5100,5400,
60,2600,5100,4800,4900,5000,
55,2400,4900,4500,4600,4800,
50,2200,4600,4200,4300,4500,
45,2000,4300,4000,4100,4200,
40,1700,4100,3800,3800,3900,
35,1500,3800,3500,3600,3700,
30,1300,3500,3200,3300,3400,
25,1100,3100,3000,3000,3200,
20,1100,2800,2800,2800,2900,
15,1100,2400,2500,2600,2700,
10,1100,1900,2200,2300,2300,
5,1100,1600,2000,2000,2100,
`

**Comment by trader-payne** [comment]
Is it possible to change which fans belong to a group? 

I have an 4U AMD Genoa system that has an active CPU cooler on it, which is named FAN4 in supermicro's ipmi.

I want to have all the other fans to be assigned to HDD zone, and only that cpu fan to be in the CPU zone.

Thanks!

**Comment by hanjo** [comment]
I have just deployed this (in docker) on my SuperMicro H12SSL-i running TrueNAS, and it looks like everything is working fine. Thanks! 👍

**Comment by petersulyok** [comment]
> Is it possible to change which fans belong to a group?
> 
> I have an 4U AMD Genoa system that has an active CPU cooler on it, which is named FAN4 in supermicro's ipmi.
> 
> I want to have all the other fans to be assigned to HDD zone, and only that cpu fan to be in the CPU zone.
> 
> Thanks!

You cannot redefine the fan-zone assignment in IPMI, but you may want to check [Swapped Zones](https://github.com/petersulyok/smfc?tab=readme-ov-file#3-swapped-zones) feature.

**Comment by EvilOlaf** [comment]
x10dri-t works
